### ISSUE TITLE
[question] pass data from defineChunk() to handleChunk()

### ISSUE THREAD

**Issue by imClement** [Sammyjo20/laravel-chunkable-jobs#9]
Is there a way to prepare a collection in defineChunk() and then use each element of the collection in handleChunk() ?

I am trying to find out which of the following 2 scenarios is recommended:

Option 1 - use Haystack without Chunkable  
```php

$haystack = Haystack::build()
   ->addJob(new PrepareCollectionAndAppendNewJobsForEachElement_StakableJob)
   ->dispatch();
```

Option 2 - use Chunkable 
```php
$haystack = Haystack::build()
   ->addJob(new PrepareCollectionAndHandleChunksForEachElement_ChunkableJob)
   ->dispatch();
```

Any suggestion is appreciated.

**Comment by Sammyjo20** [comment]
Hey! Yes there is, if you are using Haystack, you can use the HaystackChunkableJob (you need to use the Haystack one as it will append jobs to the Haystack)

After that, in the defineChunk() method you can just set properties onto the job and “magically” that property will be available inside of handleChunk()!

e.g

```php

protected Collection $collection;

protected function defineChunk()
{
    $this->collection = collect([1,2,3])

    return Chunk…
}

protected function handleChunk()
{
    $collection = $this->collection;
}
```

Alternatively you can still use setHaystackData inside of the defineChunk and then getHaystackData inside handleChunk. 

What is your use case?

**Comment by Sammyjo20** [comment]
Docs for setting it up: https://docs.laravel-haystack.dev/cool-features/chunking-jobs

**Comment by imClement** [comment]
Thank you, Sam,

My use case it to execute a collection of pending transactions.
